apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfg
data:
  dtip:     http://dependency-track-service:8080
  branch:   master
  name:     https://github.com/0c34/govwa
  dbip:     {{ .Release.Name }}-mongodb