apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-db
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-cdx