apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependency-track
  template:
    metadata:
      labels:
        app: dependency-track
    spec:
      containers:
      - name: dependency-track
        image: dependencytrack/bundled
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: dependency-track-volume
          mountPath: /data
      volumes:
      - name: dependency-track-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: dependency-track-service
spec:
  type: NodePort
  selector: 
    app: dependency-track
  ports:
    - protocol: TCP
      name: front
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: 30100